on:
  push:
    paths:    
    - 'website/geoDesc/**'
name: zWEB UP geoDesc

jobs:
  deployGeoDesc:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy geoDesc Node
        uses: appleboy/ssh-action@v0.1.2
        with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USERNAME }}
         password: ${{ secrets.SSH_PASSWORD }}
         script: |
               cd geoBoundaries
               git fetch --all
               git checkout -b bB
               git reset --hard origin/main
               git pull https://github.com/wmgeolab/geoBoundaries.git
               cd website/geoDesc
               npm install
               npm install @material-ui/core
               npm install @material-ui/lab
               npm install react-data-table-component
               export MapboxAccessToken=${{ secrets.MAPBOX }}
               PORT=80
               kill $(sudo netstat -anp | awk '/ LISTEN / {if($4 ~ ":80$") { gsub("/.*","",$7); print $7; exit } }')
               nohup npm start >> nohup.out 2>&1 &
